version: '3'

services:
  server:
    restart: always
    container_name: app_backend
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgreSqlDb
      POSTGRES_PORT: 5432
    depends_on:
      - postgreSqlDb

  postgreSqlDb:
    restart: on-failure
    container_name: postgreSqlDb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: actualdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgreSqlDbData:/var/lib/postgresql/data

  pgadmin:
    restart: always
    container_name: pgadmin
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgreSqlDbData:

