version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bosia2202+-
      POSTGRES_DB: ActualDataBase
    ports:
      - "5432:5432"
