spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/testdb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
jwtTokenConfiguration:
  secretKey: 5ec1854e91f8a908e2e33cdef2e7e1d92881641cfcb4e4c291b16c26a628214c
  jwtLifeTime: 12h